### PR TITLE
fix: Removed transliteration of CMDR name

### PR DESCRIPTION
**Pull request by itssimple**

### CODE REVIEW

**Review by kenneaal — APPROVED** [review]
LGTM. Probably does not need 3 reviewers in the future. Unless there's eval() involved. In that case, definitely 3 reviewers. ;)

**Comment by itssimple** [comment]
I mean, I could always skip the other two, but yeah. Maybe not three.

**Review by SuperManifolds — COMMENTED** [review]
Just to confirm, this removes the transofmration from the actual CMDR name but it keeps it on the IRC nick, right?

**Comment by itssimple** [comment]
@xlexi Yes, it will only remove transliteration of the CMDR Name, not the IRC nickname. They are two separate functions.

**Review by SuperManifolds — APPROVED** [review]
LGTM

**Comment by itssimple** [comment]
https://github.com/FuelRats/Kiwi-RescuePlugin/blob/9f5fe3dfc193397f5ecbc34377699137d64dca15/script.js#L109-L131

**Pull request merged**
